### ISSUE TITLE
Unrecognised Option '-b'

### ISSUE THREAD

**Issue by EmanH** [JamesBremner/Pack#1]
When testing the file after building, I get the following error:

```
packit4me2 -b 0:ft:1:5x5x5 -i 0:ft:0:1:1x1x1 -s b -o result
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >'
  what():  unrecognised option '-b'
```

**Comment by JamesBremner** [comment]
The 'unrecognised option' error message indicates that you have passed a command line option that the program does not recognize.

In your case, you are using single dashes instead of double dashes.  It looks like you are trying to use the old style options.  Not recommended unless you are trying to support a legacy application.

Try this:

`packit4me2 --b 0:ft:1:5x5x5:1 --i 0:ft:0:1:1x1x1:0.1 --o result`

Note that the new options expect an extra field in the bin and item specs: the weight.

For a complete list of recognized options:

packit4me --help

**Comment by EmanH** [comment]
Ah I see. works fine now.
